using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace comp_shop
{
    public partial class ShowInfoForm : Form
    {
        
        public List<Item> itemsForSupplier = new List<Item>();
        public List<ItemOrdersEntity> ordersToItems = new List<ItemOrdersEntity>();

        public ShowInfoForm()
        {
            InitializeComponent();

        }

        private void ConnectedInfo_Load(object sender, EventArgs e)
        {
            // проверка для чего было вызвано окно
            // загузка оформленных заказов на текущий товар
            if (this.Text == "Заказы товара")
            {
                dataGridView1.AutoGenerateColumns = true;
                dataGridView1.DataSource = MainForm.currentItemOrdersEntities;
                button1.Text = "Готово";
            }
            // загрузка товаров текущего заказа 
            else if (this.Text == "Товары в заказе")
            {
                dataGridView1.AutoGenerateColumns = true;
                dataGridView1.DataSource = MainForm.currentItemOrdersEntities;
                button1.Text = "Готово";
            }
            // загрузка товаров текушего поставщика
            else if (this.Text == "Товары поставщика")
            {
                dataGridView1.AutoGenerateColumns = true;
                dataGridView1.DataSource = MainForm.currentItems;
                button1.Text = "Готово";
            }
            // загрузка всех товаров или поставщиков для выбора
            else if (this.Text == "Выбор поставщика")
            {
                dataGridView1.AutoGenerateColumns = true;
                dataGridView1.DataSource = DB.ShowAllSuppliers();
                button1.Text = "Выбрать";
            }
            else
            {
                dataGridView1.AutoGenerateColumns = true;
                dataGridView1.DataSource = DB.ShowAllItems();
                button1.Text = "Выбрать";
            }

            DataGridViewHeadersRename();

            // настройка ширины колонок
            dataGridView1.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells;
            dataGridView1.AutoResizeColumns();
        }

        private void dataGridViewHeadersNaming()
        {

        }

        private void dataGridView1_DataError(object sender, DataGridViewDataErrorEventArgs e)
        {

        }


        // обработка двойного клика
        private void dataGridView1_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            // если выбор товара из всех имеющихся
            if (this.Text == "Выбор товара")
            {
                ItemChoose();
            }
            // если выбор поставщика из всех имеющихся
            else if (this.Text == "Выбор поставщика")
            {
                SupplierChoose();
            }
        }

        // нажатие кнопки выбрать / готово
        private void button1_Click(object sender, EventArgs e)
        {
            // если выбор товара из всех имеющихся
            if (this.Text == "Выбор товара")
            {
                ItemChoose();
            }
            // если выбор поставщика из всех имеющихся
            else if (this.Text == "Выбор поставщика")
            {
                SupplierChoose();
            }
            else { this.Close(); }
        }

        // нажатие кнопки отмена
        private void button2_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        // поиск выбранного товара
        private void ItemChoose()
        {
            DataGridViewSelectedRowCollection rows = dataGridView1.SelectedRows;
            MainForm.currentItem = DB.SearchItemByNameOrID(ID: Convert.ToInt32(rows[0].Cells[0].Value))[0];
            this.Close();
        }

        // поиск выбранного поставщика
        private void SupplierChoose()
        {
            DataGridViewSelectedRowCollection rows = dataGridView1.SelectedRows;
            MainForm.currentSupplier = DB.SearchSupplier(supplierID: Convert.ToInt32(rows[0].Cells[0].Value));
            this.Close();
        }

        //переименование заголовков таблицы
        private void DataGridViewHeadersRename()
        {

            List<string> autoGeneratedHeaders = new List<string> {
            "ItemID",
            "Name",
            "Price",
            "Supplier",
            "SupplierID",
            "Contacts",
            "Category",
            "OrderID",
            "SellerName",
            "Item",
            "Customer",
            "CustomerContact",
            "OrderDate",
            "Quantity",
            };

            List<string> correctHeaders = new List<string> {
            "ID товара",
            "Название",
            "Цена",
            "Поставщик",
            "ID поставщика",
            "Контакты",
            "Категория",
            "ID заказа",
            "Имя продавца",
            "Товар",
            "Покупатель",
            "Контакты покупателя",
            "Дата заказа",
            "Количество"
            };


            // сопоставление заголовков автогенерации и необходимых заголовков
            for (int i = 0; i < dataGridView1.Columns.Count; i++)
            {
                for (int j = 0; j < autoGeneratedHeaders.Count; j++)
                {
                    try
                    {
                        if (dataGridView1.Columns[i].HeaderText == autoGeneratedHeaders[j])
                        {
                            dataGridView1.Columns[i].HeaderText = correctHeaders[j];
                        }
                        // сокрытие лишних колонок
                        else if (dataGridView1.Columns[i].HeaderText == "CategoryID" ||
                            dataGridView1.Columns[i].HeaderText == "Items" ||
                            dataGridView1.Columns[i].HeaderText == "OrderItems")
                        {
                            dataGridView1.Columns[i].Visible = false;
                        }
                    }
                    catch
                    { }
                }
            }
            //try
            //{
            //    // сокрытие лишних колонок
            //    dataGridView1.Columns["CategoryID"].Visible = false;
            //    dataGridView1.Columns["Items"].Visible = false;
            //    dataGridView1.Columns["OrderItems"].Visible = false;
            //}
            //catch { }
        }

       
    }
}
